{% set name = "joypy" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 55d268386a1d2d974aa90cbf6dcca3ad943d17075987dfb8c4a772852fbe79c7

build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base
    - numpy
    - pandas >=0.20.0
    - python >={{ python_min }}
    - scipy >=0.11.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - joypy

about:
  home: http://github.com/sbebo/joypy
  license: MIT
  license_file: LICENSE
  summary: Joyplots in python
  dev_url: http://github.com/sbebo/joypy

extra:
  recipe-maintainers:
    - dirmeier
