{% set name = "joypy" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ce768cdee9a66c81dbdffef8b17612457c948bd706587b8cd333da01ff6587d

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib-base
    - numpy
    - pandas >=0.20.0
    - python
    - scipy >=0.11.0

test:
  imports:
    - joypy

about:
  home: http://github.com/sbebo/joypy
  license: MIT
  license_file: LICENSE
  summary: Joyplots in python
  dev_url: http://github.com/sbebo/joypy

extra:
  recipe-maintainers:
    - dirmeier
