travis:
  secure:
    BINSTAR_TOKEN: 5MUXGcPzGSvMkmuoVe9Zvk+2Pd5CLtNu8/0OQknbrZAQNoPmKIzGcpPvHY+zac1LfG+wi379B1MnlpdKRpsCITGXfwAggv1zEEMRBJi8LCTS2tGb3G0Pww1ABPU6iizysIcM3Q8KzGf//FIL7Sc2J7tBgPvX317lHoiVgZ+8f9o+lPlDfi4ceeVjvm+4RsB7s2yvNF440xHQsiPxaTyKX7dfrKpnBOdcvYI61z2Buz2a46GT5/S3K3SxGf5JXS3omjDb/1KBIZt0/WL6bxur34wmOAD9lhdOJdrBrLR/JhlHVq0u+kvwTHpNkKpa73hp5vYHiUuG/YORXRYaPHlwV/JXSGUbEzBTrzlZDJ7IJYzhRLBkyB5TQ1I1Iwhhy7CqfBvtnEbwcDurqrivj++C0nU4S3kKrU7ntognMqgsyNLOib6g+rskUB5ZN4xPMRC1vDB0/rfRNsw/N+P13aeaVacY1BBropiA4wIye2VXqIIca13kJ2jLyZnuTb0e63fgBiTFImSWpy25fioWuN11iInY8cCfUQdGJFE6gDebQL9M2JMgThoT7mHmJhdMUU+IVVOQsYvzk53/BppRelBFm0qq40Hfm8RBi6+EO4zYTUHkSiD87/ks8nVI0NJOL+u9EstJBzAu5IOqYBX6g+f87eIFthhLP0zyAEJFtDounZk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
